services:
  ujikom-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ujikom-backend
    restart: unless-stopped
    ports:
      - '3006:8080'
    env_file:
      - .env
    networks:
      - ujikom-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/api/v1/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  ujikom-network:
    driver: bridge
